truecharts/library-charts

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_mongodbInit.tpl
Same reason as https://github.com/truecharts/apps/pull/2329
=> chore(mongodb): adjust init

charts/common/Chart.yaml, charts/common/templates/lib/chart/_values.tpl
=> feat(common): set NETCAP when hostNetwork

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_redisInjector.tpl
=> fix(redisInjector): include port in plainporthost

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_mongodbInjector.tpl
=> fix(mongodb): actuallly inject replicaset key

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_mongodbInjector.tpl
=> revert(mongodb): revert mongodb replicaset

charts/common/Chart.yaml, charts/common/templates/addons/vpn/wireguard/_container.tpl
=> fix(wireguard): use nft for IPTABLES

charts/common/templates/class/_configmap.tpl, charts/common/templates/class/_ingress.tpl, charts/common/templates/class/_networkPolicy.tpl, charts/common/templates/class/_pvc.tpl, charts/common/templates/class/_rbac.tpl, charts/common/templates/class/_secret.tpl, charts/common/templates/class/_service.tpl, charts/common/templates/class/_serviceaccount.tpl, charts/common/templates/lib/controller/_container.tpl, charts/common/templates/lib/controller/_pod.tpl, charts/common/templates/lib/controller/_ports.tpl, charts/common/templates/lib/controller/_prepare.tpl, charts/common/templates/lib/controller/_volumeMounts.tpl, charts/common/templates/lib/controller/_volumes.tpl, charts/common/templates/lib/dependencies/_mariadbInit.tpl, charts/common/templates/lib/dependencies/_mongodbInit.tpl, charts/common/templates/lib/dependencies/_postgresInit.tpl, charts/common/templates/pods/_daemonset.tpl, charts/common/templates/pods/_deployment.tpl, charts/common/templates/pods/_statefulset.tpl, charts/common/values.yaml, tests/library/common/autoPermissions_spec.rb
=> More TPL usage for containers and pods

charts/common/templates/SCALE/_externalInterfaces.tpl, charts/common/templates/SCALE/_portal.tpl, charts/common/templates/lib/util/_storage.tpl, charts/common/templates/lib/values/_supplementalGroups.tpl, charts/common/templates/spawner/_ingress.tpl, charts/common/values.yaml, tests/library/common/cert_spec.rb, tests/library/common/portal_spec.rb, tests/library/common/pvc_spec.rb
=> Ensure SCALE specific code is not run outside of SCALE

charts/common/templates/lib/controller/_pod.tpl, charts/common/values.yaml, helper-charts/common-test/tests/pod/installcontainers_test.yaml, helper-charts/common-test/tests/pod/network_test.yaml, helper-charts/common-test/tests/pod/upgradecontainers_test.yaml, helper-charts/common-test/tests/portal/defaults_test.yaml, helper-charts/common-test/tests/portal/metadata_test.yaml, helper-charts/common-test/tests/portal/nodeport_test.yaml, helper-charts/common-test/tests/portal/overrides_test.yaml, unittests.md
=> some more work on tests

charts/common/Chart.yaml, charts/common/templates/lib/controller/_container.tpl
⚒️ Fixes  https://github.com/truecharts/apps/issues/1807
Based the fix from `extraArgs` which it's tpl works on list
**📃 Notes:**
=> fix(container): fix command list tpl

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl, charts/common/templates/lib/dependencies/_solrInjector.tpl, charts/common/templates/loader/_init.tpl, charts/common/values.yaml
=> feat(solr): add solr

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl
Adds informational output to ClickHouse init container
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(prepare): add stdout output for ClickHouse init container

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl
=> chore(solr): add output on init

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_clickhouseInjector.tpl
This should fix the following error:
```text
Error: UPGRADE FAILED: template: plausible/templates/common.yaml:2:4: executing "plausible/templates/common.yaml" at <include "tc.common.loader.init" .>: error calling include: template: plausible/charts/common/templates/loader/_init.tpl:32:6: executing "tc.common.loader.init" at <include "tc.common.dependencies.clickhouse.injector" .>: error calling include: template: plausible/charts/common/templates/lib/dependencies/_clickhouseInjector.tpl:11:16: executing "tc.common.dependencies.clickhouse.injector" at <index .stringData "clickhouse-password">: error calling index: index of untyped nil
```
⚒️ Fixes  # 
**📃 Notes:**
If this PR is an app …
=> fix(clickhouse): Use .data instead of .stringData to retreive clickhouse password

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_redisInjector.tpl
=> chore(redisinj): add plainhostpass

charts/common/Chart.yaml, charts/common/templates/lib/controller/_pod.tpl
⚒️ Fixes  https://github.com/truecharts/charts/issues/3444
**📃 Notes:**
---
=> fix(dnsPolicy): fix lists where was initialized as empty always

charts/common/Chart.yaml, charts/common/templates/addons/vpn/_vpn.tpl, charts/common/templates/addons/vpn/tailscale/_addon.tpl, charts/common/templates/addons/vpn/tailscale/_container.tpl, charts/common/templates/addons/vpn/tailscale/_secret.tpl, charts/common/values.yaml
⚒️ Fixes  #https://github.com/truecharts/charts/issues/1347
**📃 Notes:**
---
=> feat(tailscale-addon): add tailscale-addon

charts/common/Chart.yaml, charts/common/templates/addons/vpn/_vpn.tpl, charts/common/templates/lib/controller/_prepare.tpl
=> fix(vpn): don't do anything with config file if type is tailscale

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl
=> fix(init): use new mongo shell

charts/common/Chart.yaml, charts/common/templates/addons/vpn/tailscale/_container.tpl
=> chore(tailscale): remove variables that not relevant

charts/common/Chart.yaml, charts/common/templates/lib/controller/_container.tpl, charts/common/values.yaml, helper-charts/common-test/tests/container/env_test.yaml, helper-charts/common-test/tests/controller/metadata_daemonset_test.yaml, helper-charts/common-test/tests/controller/metadata_deployment_test.yaml, helper-charts/common-test/tests/controller/metadata_statefulset_test.yaml
=> fix(puid/pgid): only set them when running as root, and not explicitly disabled

charts/common/Chart.yaml, charts/common/templates/class/_serviceaccount.tpl
=> fix(ServiceAccount): fix capitalization and annotation reference

charts/common/Chart.yaml, charts/common/templates/addons/vpn/tailscale/_addon.tpl, charts/common/templates/addons/vpn/tailscale/_container.tpl, charts/common/templates/addons/vpn/tailscale/_rbac.tpl, charts/common/templates/addons/vpn/tailscale/_sa.tpl, charts/common/values.yaml
⚒️ Fixes  https://github.com/truecharts/charts/issues/3718
**📃 Notes:**
---
=> fix(tailscale-addon): add SA, CR, CRB

charts/common/Chart.yaml, charts/common/templates/addons/vpn/tailscale/_addon.tpl, charts/common/templates/addons/vpn/tailscale/_container.tpl
=> fix(tailscale): render secret

charts/common/Chart.yaml, charts/common/values.yaml, helper-charts/common-test/tests/container/volumemounts_test.yaml
=> feat(/dev/shm): mount /dev/shm to memory for all containers by default

charts/common/templates/class/_rbac.tpl, charts/common/templates/class/_serviceaccount.tpl
=> chore(common): remove unused variables

charts/common/Chart.yaml, charts/common/values.yaml
=> bump multi-init and common

charts/common/Chart.yaml, charts/common/templates/addons/vpn/tailscale/_addon.tpl
=> fix(tailscale-addon): fix indentation on includes

cspell.config.yaml, helper-charts/common-test/tests/addons/vpn_test.yaml
=> add tests for tailscale addon

.github/workflows/charts-lint-test.yaml, charts/common/Chart.yaml, charts/common/templates/addons/vpn/tailscale/_addon.tpl, charts/common/templates/lib/controller/_prepare.tpl, charts/common/templates/lib/dependencies/_solrInjector.tpl
=> fix(solr): add missing plainhost key in secret

charts/common/Chart.yaml, charts/common/templates/class/_pvc.tpl, charts/common/values.yaml
=> fix(pvc): revert size change

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_solrInjector.tpl
=> fix(solr): fix solr URL

charts/common/Chart.yaml, charts/common/templates/lib/util/_crd-updater.tpl
=> fix(crds): fix volumeMounts name of crds

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl
Requires https://github.com/truecharts/containers/pull/9772
To be merged first 
**📃 Notes:**
---
=> fix(common): Use correct acl binary

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl, charts/common/templates/lib/util/_crd-updater.tpl
=> fix(auto-perms): don't try recursive on file

charts/common/Chart.yaml, charts/common/templates/lib/util/_crd-updater.tpl, charts/common/templates/lib/util/_manifest-updater.tpl, charts/common/values.yaml, helper-charts/common-test/ci/basic-values.yaml, helper-charts/common-test/ci/manifest-values.yaml, helper-charts/common-test/ci/stagingmanifest-values.yaml, helper-charts/common-test/values.yaml
This moves the manifests to a github repository hosted by us.
This allows us to removed the versioning from common and always ensure the latest version is loaded.
**📃 Notes:**
---
=> feat(common): grab manifests from github

charts/common/Chart.yaml, charts/common/templates/lib/dependencies/_cnpgInjector.tpl
=> fix(cnpg-common): ensure cnpg url's point to the correct pooler URLs

charts/common/Chart.yaml, charts/common/values.yaml
=> chore(tailscale): update TS image

charts/common/Chart.yaml, charts/common/values.yaml
=> Update tailscale image

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl, charts/common/templates/lib/util/_manifest-updater.tpl
=> fix(prepare): rename auto-perm container and allow to run as root - fix manifest-updater

charts/common/Chart.yaml, charts/common/templates/lib/controller/_prepare.tpl
=> fix(mongodb): it really wants to write on history file

LICENSE, library/common-test/LICENSE, library/common/LICENSE
A new license to prevent integration of the TrueCharts apps, into another production (commercial) product with the intent of having other people install our apps in production.
However: Our apps can still be used in production and modified just fine by everyone. 
**📃 Notes:**
---
=> Relicensing

library/common/Chart.yaml, library/common/values.yaml
=> tpl probe type

library/common-test/tests/container/ports_test.yaml, library/common-test/tests/secret/validation_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_securityContext.tpl
=> add NET_BIND_SERVICE on ports <1024

library/common/Chart.yaml, library/common/templates/spawner/_cnpg.tpl
=> feat(common): allow for tpl/string for cnpg enable

library/common-test/tests/service/load_balancer_test.yaml, library/common-test/tests/service/metadata_test.yaml, library/common/Chart.yaml, library/common/templates/loader/_apply.tpl, library/common/templates/values/_validate.tpl
=> scan all values for helm produced errors for yaml

library/common/Chart.yaml, library/common/templates/lib/chart/_names.tpl
=> chore(validation): update name validation regex, to not allow `--`

library/common/Chart.yaml, library/common/templates/spawner/_portal.tpl
=> fix(common): disable removing port due to iX bug

library/common-test/tests/container/securityContext_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_securityContext.tpl
=> Add CHOWN cap when runnign as root, as its needed 99% of the time

.github/workflows/common_library_tests.yaml, library/common-test/tests/persistence/validation_test.yaml, library/common-test/tests/pod/volume_configmap_test.yaml, library/common-test/tests/pod/volume_secret_test.yaml, library/common/templates/lib/pod/volumes/_configmap.tpl, library/common/templates/lib/pod/volumes/_secret.tpl, run_common_tests.sh
=> Adds a check that the configmap/secret defined in persistence exists

library/common-test/tests/container/env_test.yaml, library/common-test/tests/container/volumeMounts_test.yaml, library/common-test/tests/pod/volume_emptyDIr_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_env.tpl, library/common/templates/lib/pod/volumes/_emptyDir.tpl, library/common/templates/loader/_init.tpl, library/common/templates/loader/_lists.tpl, library/common/templates/values/lists/_persistenceList.tpl, library/common/values.yaml
⚒️ Fixes  # 
Will also add persistence list later today
**📃 Notes:**
---
=> fix(common): correctly add persistenceList and misc fixes

library/common-test/tests/service/list_test.yaml, library/common/Chart.yaml, library/common/templates/loader/_lists.tpl, library/common/templates/values/lists/_serviceList.tpl, library/common/values.yaml
=> fix(common): ensure serviceList is correctly parsed

library/common-test/tests/addons/netshoot_test.yaml, library/common-test/tests/container/env_test.yaml, library/common-test/tests/service/external_ip_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_env.tpl, library/common/templates/lib/endpointSlice/_ports.tpl
⚒️ Fixes  https://github.com/truecharts/charts/issues/7936
**📃 Notes:**
---
=> Fix endpointSlice

library/common-test/tests/container/securityContext_test.yaml, library/common-test/tests/container/volumeMounts_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_securityContext.tpl, library/common/templates/lib/container/_volumeMounts.tpl, library/common/templates/loader/_lists.tpl, library/common/templates/values/lists/_deviceList.tpl, library/common/templates/values/lists/_persistenceList.tpl, library/common/values.yaml
⚒️ Fixes part of https://github.com/truecharts/charts/issues/7941
⚒️ Fixes https://github.com/truecharts/charts/issues/7943
**📃 Notes:**
---
=> Fix(common): default mountPath to hostPath on device type, add deviceList and set allowPrivEsca to true when privileged is true

library/common-test/tests/container/envFixed_test .yaml, library/common-test/tests/initContainer/data_test.yaml, library/common-test/tests/initContainer/data_upgrade_test.yaml, library/common-test/tests/pod/securityContext.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_fixedEnv.tpl, library/common/templates/lib/pod/_podSecurityContext.tpl
⚒️ Fixes  https://github.com/truecharts/charts/issues/7955
Fixes transcoding issue https://discord.com/channels/830763548678291466/1096125658498867252/1096146172911030282
**📃 Notes:**
---
=> Add void caps for nvidia when no gpu is selected

library/common-test/tests/addons/codeserver_test.yaml, library/common/Chart.yaml, library/common/templates/addons/code-server/_codeserver.tpl, library/common/templates/addons/code-server/_container.tpl, library/common/templates/addons/netshoot/_container.tpl, library/common/templates/addons/vpn/_gluetunContainer.tpl, library/common/templates/addons/vpn/_openvpnContainer.tpl, library/common/templates/addons/vpn/_tailscaleContainer.tpl, library/common/templates/addons/vpn/_wireguardContainer.tpl, library/common/values.yaml
⚒️ Fixes https://github.com/truecharts/charts/issues/7932
⚒️ Fixes https://github.com/truecharts/charts/issues/7949
⚒️ Fixes https://github.com/truecharts/charts/issues/7973
**📃 Notes:**
---
=> fix(addons): Addons -> add net_raw capability, codeserver -> mark svc primary when no other exists

library/common-test/tests/addons/vpn_test.yaml, library/common-test/tests/service/list_test.yaml, library/common/Chart.yaml, library/common/templates/addons/vpn/_gluetunContainer.tpl, library/common/templates/addons/vpn/_volume.tpl, library/common/templates/values/lists/_serviceList.tpl
=> fix(vpn): fix configFile mountpath on wg/ovpn and give gluetun more perms and fix svcList

library/common-test/tests/service/list_test.yaml, library/common/Chart.yaml, library/common/templates/values/lists/_portList.tpl, library/common/templates/values/lists/_serviceList.tpl
=> fix(portList): fix port list in service

library/common-test/tests/addons/vpn_test.yaml, library/common-test/tests/container/resources_test.yaml, library/common/Chart.yaml, library/common/templates/addons/code-server/_container.tpl, library/common/templates/addons/vpn/_gluetunContainer.tpl, library/common/templates/addons/vpn/_openvpnContainer.tpl, library/common/templates/addons/vpn/_wireguardContainer.tpl, library/common/templates/lib/container/_resources.tpl
⚒️ Fixes https://github.com/truecharts/charts/issues/8004
⚒️ Fixes https://github.com/truecharts/charts/issues/8013 (OVPN needs MKNOD)
**📃 Notes:**
---
=> fix(resources): correctly handle "0" gpu

library/common-test/tests/addons/vpn_test.yaml, library/common-test/tests/container/envFixed_test .yaml, library/common-test/tests/initContainer/data_test.yaml, library/common-test/tests/initContainer/data_upgrade_test.yaml, library/common-test/tests/pod/runtime_class_name_test.yaml, library/common-test/tests/pod/securityContext.yaml, library/common/Chart.yaml, library/common/templates/addons/vpn/_openvpnContainer.tpl, library/common/templates/addons/vpn/_volume.tpl, library/common/templates/addons/vpn/_wireguardContainer.tpl, library/common/templates/lib/container/_fixedEnv.tpl, library/common/templates/lib/pod/_podSecurityContext.tpl, library/common/templates/lib/pod/_runtimeClassName.tpl, library/common/templates/spawner/_portal.tpl
⚒️ Fixes https://github.com/truecharts/charts/issues/8009
⚒️ Fixes https://github.com/truecharts/charts/issues/8008
⚒️ Fixes https://github.com/truecharts/charts/issues/7984
⚒️ Fixes https://github.com/truecharts/charts/issues/7985
⚒️ Fixes https://github.com/truecharts/charts/issues/8006
**📃 Notes:**
---
=> fix(vpn,podSecContext,portal,gpu): fix wg, vpn mountpaths, portal protocol, fsGroup 0 handling, gpu

library/common-test/tests/service/external_ip_test.yaml, library/common/Chart.yaml, library/common/templates/class/_service.tpl, library/common/templates/helpers/_getPortRange.tpl
⚒️ Fixes https://github.com/truecharts/charts/issues/7983
⚒️ Fixes https://github.com/truecharts/charts/issues/8028
**📃 Notes:**
---
=> fix(portcheck,externalip): Convert everything to int for port check and fix protocol check logic for externalIP type

library/common/Chart.yaml, library/common/templates/addons/vpn/_gluetunContainer.tpl, library/common/templates/addons/vpn/_wireguardContainer.tpl
⚒️ Fixes  https://github.com/truecharts/charts/issues/8047
**📃 Notes:**
---
=> fix(vpn): more caps for wg and gluetun

library/common-test/tests/externalInterface/validation_test.yaml, library/common/Chart.yaml, library/common/templates/lib/externalInterface/_validation.tpl
⚒️ Fixes part of https://github.com/truecharts/charts/issues/8052
**📃 Notes:**
---
=> fix(externalInterfaces): One level deeper

library/common-test/tests/container/envFixed_test .yaml, library/common/templates/lib/container/_fixedEnv.tpl
=> chore(nvidia): dont allow overrides

library/common-test/default-values.yaml, library/common-test/tests/defaults/defaults-test.yaml, library/common/Chart.yaml, library/common/templates/class/_cronjob.tpl, library/common/templates/class/_daemonset.tpl, library/common/templates/class/_deployment.tpl, library/common/templates/class/_job.tpl, library/common/templates/class/_statefulset.tpl, library/common/templates/lib/metadata/_selectorLabels.tpl, library/common/templates/lib/workload/_cronjobSpec.tpl, library/common/templates/lib/workload/_jobSpec.tpl, library/common/values.yaml
⚒️ Fixes  https://github.com/truecharts/charts/issues/8098
**📃 Notes:**
---
=> fix(varrun, devshm): medium -> Memory

library/common-test/tests/service/external_ip_test.yaml, library/common/Chart.yaml, library/common/templates/class/_endpoint.tpl, library/common/templates/class/_service.tpl, library/common/templates/lib/endpoint/_addresses.tpl, library/common/templates/lib/endpoint/_ports.tpl
=> chore(Endpoint): Add endpoint class and tests

library/common-test/tests/service/external_ip_test.yaml, library/common/Chart.yaml, library/common/templates/class/_endpoint.tpl
=> fix(endpoint): use plural for kind

library/common-test/tests/defaults/defaults-test.yaml, library/common-test/tests/pod/securityContext.yaml, library/common/Chart.yaml, library/common/templates/lib/pod/_podSecurityContext.tpl, run_common_tests.sh
=> chore(supplementalGroups): Adds 568 to supplementalGroups always

library/common-test/Chart.yaml, library/common/Chart.yaml, library/common/templates/lib/dependencies/_clickhouseInjector.tpl, library/common/templates/lib/dependencies/_dbWait.tpl, library/common/templates/lib/dependencies/_mariadbInjector.tpl, library/common/templates/lib/dependencies/_mongodbInjector.tpl, library/common/templates/lib/dependencies/_redisInjector.tpl, library/common/templates/lib/dependencies/_solrInjector.tpl
⚒️ Fixes https://github.com/truecharts/charts/issues/8115
⚒️ Fixes https://github.com/truecharts/charts/issues/7963
**📃 Notes:**
---
=> fix(deps): use the correct, decrypted, credentials

library/common-test/tests/container/ports_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_ports.tpl
⚒️ Fixes  # 
Applies a partial fix for this issue mentioned here:
https://github.com/k3s-io/k3s/discussions/6289
**📃 Notes:**
---
=> fix(container/ports): fix an issue with hostNetwork toggling

library/common-test/tests/cnpg/stop_test.yaml, library/common-test/tests/cronjob/spec_test.yaml, library/common-test/tests/deployment/spec_test.yaml, library/common-test/tests/job/spec_test.yaml, library/common-test/tests/pod/node_selector_test.yaml, library/common-test/tests/statefulset/spec_test.yaml, library/common/Chart.yaml, library/common/templates/class/_cnpgCluster.tpl, library/common/templates/class/_cnpgPooler.tpl, library/common/templates/lib/pod/_nodeSelector.tpl, library/common/templates/lib/workload/_cronjobSpec.tpl, library/common/templates/lib/workload/_deployementSpec.tpl, library/common/templates/lib/workload/_jobSpec.tpl, library/common/templates/lib/workload/_statefulsetSpec.tpl
=> fix(common): cleanup stopAll changes and add some tests

library/common-test/tests/defaults/defaults-test.yaml, library/common-test/tests/pod/host_pid_test.yaml, library/common/Chart.yaml, library/common/templates/lib/pod/_hostPID.tpl, library/common/templates/lib/workload/_pod.tpl
It seems somehow this option was forgoten to be included.
**📃 Notes:**
---
=> feat(common): add hostPID support

library/common-test/tests/addons/vpn_test.yaml, library/common/Chart.yaml, library/common/templates/addons/vpn/_tailscaleContainer.tpl, library/common/templates/addons/vpn/_vpn.tpl
⚒️ Fixes  https://github.com/truecharts/charts/issues/9003
Invastigating some permissions errors, on `getLocalBackend error: store.New: creating state directory: chmod /var/lib/tailscale: operation not permitted`
When in userspace.
Also when not in userspace have to also mount /dev/net/tun
**📃 Notes:**
---
=> fix(tailscale): needs SA token

library/common-test/Chart.yaml, library/common-test/tests/defaults/defaults-test.yaml, library/common-test/tests/ingress/metadata_test.yaml, library/common-test/tests/pod/share_process_namespace_test.yaml, library/common/Chart.yaml, library/common/templates/lib/pod/_shareProcessNamespace.tpl, library/common/templates/lib/workload/_pod.tpl, library/common/values.yaml
=> feat(common): add support for shareProcessNamespace

library/common/templates/class/_ingress.tpl, library/common/templates/class/_route.tpl
=> fix(Common): Fix ingress typo

library/common-test/tests/defaults/defaults-test.yaml, library/common/Chart.yaml, library/common/values.yaml
=> chore(ndots): default to 1

library/common/Chart.yaml, library/common/templates/lib/util/_tc_namespace.tpl
=> fix(common): use pre-install hook for `tc-system` namespace creation

library/common-test/tests/operator/operator_test.yaml, library/common/templates/lib/util/_register_operator.tpl, library/common/templates/lib/util/_tc_namespace.tpl, library/common/templates/lib/util/_verify_operator.tpl, library/common/templates/loader/_init.tpl
=> fix(operators): update logic for verifying and registering

library/common-test/values.yaml, library/common/Chart.yaml, library/common/templates/lib/util/_verify_operator.tpl, library/common/values.yaml
We need to actually save the found operator data for use with the charts
We also need an option to start deploying this in a soft-failing way
**📃 Notes:**
---
=> feat(common): tweak operator verification behavior

library/common/templates/lib/util/_verify_operator.tpl
=> feat(common): fix operator verify values.yaml input and add caching

library/common-test/Chart.yaml, library/common-test/tests/defaults/defaults-test.yaml, library/common-test/tests/extraTpl/extratpl_test.yaml, library/common/Chart.yaml, library/common/templates/loader/_apply.tpl, library/common/templates/spawner/_extraTpl.tpl, library/common/values.yaml
add extraTpl support for custom template file defining in values.yaml
**📃 Notes:**
---
=> feat(common): add support for additional templates defined in values.yaml

library/common/Chart.yaml, library/common/templates/lib/dependencies/_clickhouseInjector.tpl, library/common/templates/lib/dependencies/_mariadbInjector.tpl, library/common/templates/lib/dependencies/_mongodbInjector.tpl, library/common/templates/lib/dependencies/_redisInjector.tpl, library/common/templates/lib/dependencies/_solrInjector.tpl
⚒️ Fixes  # 
Since we have `exapendObjectName: false` we need to lookup in the same name as the secret is created and not the exapanded name
**📃 Notes:**
---
=> Fix db password retrievals.

library/common/Chart.yaml, library/common/templates/lib/util/_manifest_manager.tpl
=> Set ndots to 1 on manifest manager too

library/common/templates/lib/util/_verify_operator.tpl
⚒️ Fixes  # 
No changes, just flattens the code for readability.
**📃 Notes:**
---
=> chore(common): flatten the verify operator code

library/common/templates/class/_ingress.tpl, library/common/templates/lib/util/_chartcontext.tpl
=> fix(ingress): fix ingress and chartcontext namespace

library/common/Chart.yaml, library/common/templates/class/_cnpgCluster.tpl, library/common/templates/class/_cnpgPooler.tpl
CNPG was not respecting resource limts, we should fix that.
**📃 Notes:**
---
=> feat(cnpg): add resource limits for cnpg

library/common-test/tests/addons/autoperms_test.yaml, library/common/Chart.yaml, library/common/templates/lib/util/_autoperms.tpl
=> chore(autoperms): remove pvc from autoperms

library/common-test/tests/addons/autoperms_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_probes.tpl, library/common/templates/lib/container/_resources.tpl
=> fix(resources): Always make a copy of global resources before start modifications

library/common-test/ci/autopermissions-values.yaml, library/common-test/tests/addons/autoperms_test.yaml, library/common/Chart.yaml, library/common/templates/addons/vpn/_volume.tpl, library/common/templates/lib/container/_volumeMounts.tpl, library/common/templates/lib/pod/_volumes.tpl, library/common/templates/lib/util/_autoperms.tpl
=> chore(autoperms): add an `enabled` flag

library/common-test/Chart.yaml, library/common/Chart.yaml, library/common/templates/class/_podDisruptionBudget.tpl, library/common/templates/lib/podDistruptionBudget/_validation.tpl, library/common/templates/loader/_apply.tpl, library/common/templates/spawner/_podDisruptionBudget.tpl, library/common/values.yaml
poddisruptionbudget objects are rather easy to implement and offer another unique sellingpoint by being standardised.
**📃 Notes:**
---
=> feat: implement poddisruptionbudget object creation

library/common-test/tests/container/envFixed_test .yaml, library/common-test/tests/container/envList_test.yaml, library/common-test/tests/container/env_test.yaml, library/common-test/tests/pod/securityContext.yaml, library/common/Chart.yaml, library/common/templates/helpers/_makeIntOrNoop.tpl, library/common/templates/lib/container/_env.tpl, library/common/templates/lib/container/_envList.tpl, library/common/templates/lib/container/_fixedEnv.tpl, library/common/templates/lib/pod/_podSecurityContext.tpl
⚒️ Fixes  #495 
**📃 Notes:**
---
=> chore(ints): handle big ints that are converted to E notation

library/common-test/tests/podDisruptionBudget/data_test.yaml, library/common-test/tests/podDisruptionBudget/metadata_test.yaml, library/common-test/tests/podDisruptionBudget/name_test.yaml, library/common-test/tests/podDisruptionBudget/validation_test.yaml, library/common/Chart.yaml, library/common/templates/class/_podDisruptionBudget.tpl, library/common/templates/lib/podDistruptionBudget/_validation.tpl, library/common/templates/spawner/_podDisruptionBudget.tpl
=> fix(pdb): fix few issues and add tests

.github/workflows/common_library_tests.yaml, library/common/Chart.yaml, library/common/templates/spawner/_certificate.tpl, library/common/templates/spawner/_configmap.tpl, library/common/templates/spawner/_imagePullSecret.tpl, library/common/templates/spawner/_ingress.tpl, library/common/templates/spawner/_podDisruptionBudget.tpl, library/common/templates/spawner/_pvc.tpl, library/common/templates/spawner/_rbac.tpl, library/common/templates/spawner/_scaleCertificate.tpl, library/common/templates/spawner/_secret.tpl, library/common/templates/spawner/_service.tpl, library/common/templates/spawner/_serviceAccount.tpl, library/common/templates/spawner/_webhook.tpl, library/common/templates/spawner/_workload.tpl
⚒️ Fixes  # 
Only generate fullname once per spawner.
No need to do that on every loop
**📃 Notes:**
---
=> chore(optimization): reduce fullname generation on spawners

library/common/Chart.yaml, library/common/templates/lib/dependencies/_redisInjector.tpl, library/common/templates/lib/imagePullSecret/_createData.tpl
=> fix(redis-creds): do not use redisUsername if its empty

library/common/Chart.yaml, library/common/values.yaml
Add link to existing sources and the templating for adding a link to our Website's Docs section
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(Catalog): Add more info to SCALE Notes

library/common/Chart.yaml, library/common/values.yaml
=> feat(common): Update chart nodes for 23.10 SCALE catalog

library/common-test/tests/cnpg/stop_test.yaml, library/common-test/tests/cronjob/spec_test.yaml, library/common-test/tests/deployment/spec_test.yaml, library/common-test/tests/job/spec_test.yaml, library/common-test/tests/pod/node_selector_test.yaml, library/common-test/tests/statefulset/spec_test.yaml, library/common/Chart.yaml, library/common/templates/class/_cnpgCluster.tpl, library/common/templates/class/_cnpgPooler.tpl, library/common/templates/lib/pod/_nodeSelector.tpl, library/common/templates/lib/util/_stopAll.tpl, library/common/templates/lib/workload/_cronjobSpec.tpl, library/common/templates/lib/workload/_deploymentSpec.tpl, library/common/templates/lib/workload/_jobSpec.tpl, library/common/templates/lib/workload/_statefulsetSpec.tpl
=> chore(stopAll): handle scale specific case for stopping

library/common-test/Chart.yaml, library/common/Chart.yaml, library/common/templates/lib/util/_verify_operator.tpl
This adds checking for Kubernetes Reflector presence, when cluster Certificate resources are defined on clusterissuer
**📃 Notes:**
---
=> feat(common): add clusterCertificate Kubernetes Reflector checks

README.md
Added a note to tell the user to make sure the app is in the charts repo before adding it here.
**📃 Notes:**
---
=> docs(readme): Add to charts before here

library/common/Chart.yaml, library/common/templates/spawner/_certificate.tpl
⚒️ Fixes  # 
Fixes the key being checked to determine if this is a cluster cert.
**📃 Notes:**
---
=> fix(common): Update key being checked

.github/workflows/common_library_tests.yaml
Datree is no more and we need to ensure tests are actually working again
**📃 Notes:**
---
=> fix(ci): disable deprecated security scans and install cert-manager on ingress tests

library/common-test/tests/pod/topologySpreadConstraints.yaml, library/common/templates/class/_service.tpl, library/common/templates/lib/pod/_topologySpreadConstraints .tpl
=> chore(TSC): add couple extra tests on topologySpreadConstraints

library/common-test/Chart.yaml, library/common-test/ci/storageclass-values.yaml, library/common-test/tests/storageClass/metadata_test.yaml, library/common-test/tests/storageClass/names_test.yaml, library/common-test/tests/storageClass/spec_test.yaml, library/common/Chart.yaml, library/common/templates/class/_storageClass.tpl, library/common/templates/lib/storage/_storageClassValidation.tpl, library/common/templates/loader/_apply.tpl, library/common/templates/spawner/_storageClass.tpl, library/common/values.yaml
Adds support for creating storageClasses on demand through common.
Allows us for easy inclusion of more dynamic pvc provisioners on SCALE and other platforms
⚒️ Fixes  #559 
**📃 Notes:**
---
=> feat(common): add storageClass class/spawner

.github/workflows/pre-commit-check.yaml
=> run path filter with token

library/common-test/tests/volumeSnapshot/metadata_test.yaml, library/common-test/tests/volumeSnapshot/spec_test.yaml, library/common-test/tests/volumeSnapshotClass/metadata_test.yaml, library/common-test/tests/volumeSnapshotClass/names_test.yaml, library/common-test/tests/volumeSnapshotClass/spec_test.yaml, library/common/templates/class/_volumeSnapshotClass.tpl, library/common/templates/lib/storage/_validationVolumeSnapshot.tpl, library/common/templates/lib/storage/_validationVolumeSnapshotClass.tpl, library/common/templates/lib/storage/_volumeSnapshotClassValidation.tpl, library/common/templates/loader/_apply.tpl, library/common/templates/spawner/_pvc.tpl, library/common/templates/spawner/_volumeSnapshot.tpl, library/common/templates/spawner/_volumeSnapshotClass.tpl, library/common/values.yaml
With some CSI's we want to add, it's nice to also be able to spawn volumeSnapshotClass objects
⚒️ Fixes  #590
**📃 Notes:**
---
=> feat(common): Add volumeSnapshotClass class and spawner

library/common/values.yaml
=> chore(notes): cleaner notes

library/common-test/ci/backupstoragelocation-values.yaml, library/common-test/ci/volumesnapshotlocation-values.yaml, library/common-test/tests/lists/veleroBackupStorageLocationList_test.yaml, library/common-test/tests/lists/veleroVolumeSnapshotLocationList_test.yaml, library/common-test/tests/lists/volumeSnapshotClassList_test.yaml, library/common-test/tests/lists/volumeSnapshotList_test.yaml, library/common-test/tests/veleroBackupStorageLocation/metadata_test.yaml, library/common-test/tests/veleroBackupStorageLocation/names_test.yaml, library/common-test/tests/veleroBackupStorageLocation/spec_test.yaml, library/common-test/tests/veleroVolumeSnapshotLocation/metadata_test.yaml, library/common-test/tests/veleroVolumeSnapshotLocation/names_test.yaml, library/common-test/tests/veleroVolumeSnapshotLocation/spec_test.yaml, library/common-test/tests/volumeSnapshot/metadata_test.yaml, library/common-test/tests/volumeSnapshot/names_test.yaml, library/common-test/tests/volumeSnapshot/spec_test.yaml, library/common/Chart.yaml, library/common/templates/loader/_lists.tpl, library/common/templates/spawner/_volumeSnapshot.tpl, library/common/templates/spawner/velero/_backupstoragelocation.tpl, library/common/templates/spawner/velero/_volumeSnapshotLocation.tpl, library/common/templates/values/lists/_backupStorageLocationList.tpl, library/common/templates/values/lists/_volumeSnapshotClassList.tpl, library/common/templates/values/lists/_volumeSnapshotList.tpl, library/common/templates/values/lists/_volumeSnapshotLocationList.tpl, library/common/values.yaml
=> chore(common): Convert some lists to dicts (and also add list spawner)

library/common/Chart.yaml, library/common/templates/lib/util/_enabled.tpl, library/common/templates/spawner/_configmap.tpl, library/common/templates/spawner/_imagePullSecret.tpl, library/common/templates/spawner/_portal.tpl, library/common/templates/spawner/_priorityClass.tpl, library/common/templates/spawner/_pvc.tpl, library/common/templates/spawner/_rbac.tpl, library/common/templates/spawner/_scaleCertificate.tpl, library/common/templates/spawner/_secret.tpl, library/common/templates/spawner/_service.tpl, library/common/templates/spawner/_serviceAccount.tpl, library/common/templates/spawner/_storageClass.tpl, library/common/templates/spawner/_volumeSnapshot.tpl, library/common/templates/spawner/_volumeSnapshotClass.tpl, library/common/templates/spawner/_webhook.tpl, library/common/templates/spawner/_workload.tpl, library/common/templates/spawner/velero/_backupstoragelocation.tpl, library/common/templates/spawner/velero/_schedule.tpl, library/common/templates/spawner/velero/_volumeSnapshotLocation.tpl, library/common/values.yaml
=> chore(utils): use template for "enabled" with tpl support

library/common-test/tests/service/validation_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_env.tpl, library/common/templates/lib/container/_envFrom.tpl, library/common/templates/lib/pod/volumes/_configmap.tpl, library/common/templates/lib/pod/volumes/_secret.tpl, library/common/templates/lib/util/_expandName.tpl, library/common/templates/spawner/_service.tpl
=> chore(utils): use template for "expandObjectName" with tpl support

library/common-test/tests/certificate/data_test.yaml, library/common/Chart.yaml, library/common/templates/class/cert-manager/_certificate.tpl, library/common/templates/spawner/_configmap.tpl, library/common/templates/spawner/_podDisruptionBudget.tpl, library/common/templates/spawner/_priorityClass.tpl, library/common/templates/spawner/_secret.tpl, library/common/templates/spawner/_storageClass.tpl, library/common/templates/spawner/_volumeSnapshot.tpl, library/common/templates/spawner/_volumeSnapshotClass.tpl, library/common/templates/spawner/_webhook.tpl, library/common/templates/spawner/cert-manager/_certificate.tpl, library/common/templates/spawner/velero/_backupstoragelocation.tpl, library/common/templates/spawner/velero/_schedule.tpl, library/common/templates/spawner/velero/_volumeSnapshotLocation.tpl
⚒️ Fixes  #623
**📃 Notes:**
---
=> chore(common): use the expandName template in more places - also fixes a small quote bug on Certificate

library/common/Chart.yaml, library/common/templates/spawner/_podDisruptionBudget.tpl
=> chore(typo): fix typo on error msg

library/common-test/tests/ingress/traefik_test.yaml, library/common/Chart.yaml, library/common/templates/lib/ingress/integrations/_traefik.tpl
=> fix(ingress): switch middleware name and namespace

library/common-test/tests/cnpg/cluster_validation_test.yaml, library/common-test/tests/cnpg/pooler_validation_test.yaml, library/common-test/tests/cnpg/stop_test.yaml, library/common-test/tests/ingress/traefik_test.yaml, library/common/Chart.yaml, library/common/templates/class/cnpg/_cluster.tpl, library/common/templates/class/cnpg/_pooler.tpl, library/common/templates/lib/cnpg/cluster/_validation.tpl, library/common/templates/lib/cnpg/pooler/_validation.tpl, library/common/templates/lib/ingress/integrations/_traefik.tpl
fix(cnpg): hibernation wasn't working because instances cannot be 0
```shell
UPGRADE FAILED: cannot patch "meshcentral1-cnpg-main" with kind Cluster: Cluster.postgresql.cnpg.io "meshcentral1-cnpg-main" is invalid: spec.instances: Invalid value: 0: spec.instances in body should be greater than or equal to 1
```
fix(traefik): we were trying to access namespace but its an optional field.
> Moved dupe validation later, which also avoids a loop and does a more thorough dupe check (with the formatted middleware name)
⚒️ Fixes  # 
**📃 Notes:**
---
_Please don't blindly check all the boxes. Read them and only check …
=> fix(cnpg, traefik): fix hibernate and namespace errors

library/common/Chart.yaml, library/common/templates/spawner/_ingress.tpl
⚒️ Fixes  # 
Pushed to main directly, but needs a bump
https://github.com/truecharts/library-charts/commit/dd3d37310753865cc9066b9a71ef57e42360d448
**📃 Notes:**
---
=> fix(common): bump

library/common-test/tests/addons/codeserver_test.yaml, library/common/Chart.yaml, library/common/templates/addons/code-server/_codeserver.tpl, library/common/values.yaml
=> fix(codeserver): handle ingress after changes

library/common-test/tests/ingress/homepage_test.yaml, library/common/Chart.yaml, library/common/templates/lib/ingress/integrations/_homepage.tpl, library/common/values.yaml
Current parameters system is not displayable in SCALE.
**📃 Notes:**
---
=> fix(homepage integration): change structure of custom parameters

library/common-test/tests/ingress/rules_test.yaml, library/common-test/tests/ingress/tls_test.yaml, library/common/Chart.yaml, library/common/templates/class/_ingress.tpl
=> fix(ingress): handle wildcard hosts

library/common-test/tests/cnpg/pooler_metadata_test.yaml, library/common-test/tests/cnpg/stop_test.yaml, library/common/Chart.yaml, library/common/templates/class/cnpg/_pooler.tpl, library/common/templates/lib/cnpg/pooler/_spawner.tpl
=> fix(stop-all): skip creating poolers when stop-all or hibernate is enabled

library/common-test/tests/ingress/homepage_test.yaml, library/common/Chart.yaml, library/common/templates/lib/ingress/integrations/_homepage.tpl
@stavros-k part of the change already merged by accident.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix: url-> href on homepage

library/common-test/tests/service/load_balancer_test.yaml, library/common/Chart.yaml, library/common/templates/lib/service/_additionalAnnotations.tpl
=> chore(metallb): add lb ip on service as annotation

library/common/Chart.yaml, library/common/templates/lib/cnpg/cluster/_validation.tpl
=> fix(cnpg): target for backups is not mandatory

library/common-test/tests/cnpg/cluster_backup_spec_test.yaml, library/common/Chart.yaml, library/common/templates/lib/cnpg/cluster/_backup.tpl
⚒️ Fixes  # 
Fixes bug introduced in #646 
**📃 Notes:**
---
=> fix(cnpg/backup): fix rendering

library/common/Chart.yaml, library/common/templates/lib/ingress/integrations/_homepage.tpl
=> fix(homepage): try adding more sanitasion for type

library/common-test/tests/ingress/homepage_test.yaml, library/common/Chart.yaml, library/common/templates/class/_ingress.tpl, library/common/templates/lib/ingress/_targetSelector.tpl, library/common/templates/lib/ingress/integrations/_homepage.tpl
=> chore(homepage): optimize generation and add test

library/common-test/tests/ingress/rules_test.yaml, library/common/Chart.yaml, library/common/templates/class/_ingress.tpl, library/common/templates/lib/ingress/_serviceData.tpl
⚒️ Fixes  #16519
When users create custom ingress and set to point to a service, the name must be expanded in order to work, of course a flag to disable the expansion is added (`expandObjectName`) so native helm users can opt out
**📃 Notes:**
---
=> chore(ingress): expand by default the override name

.github/workflows/common_library_tests.yaml, library/common-test/Chart.yaml, library/common-test/tests/cronjob/metadata_test.yaml, library/common-test/tests/daemonset/metadata_test.yaml, library/common-test/tests/deployment/metadata_test.yaml, library/common-test/tests/ingress/homepage_test.yaml, library/common-test/tests/job/metadata_test.yaml, library/common-test/tests/pod/topologySpreadConstraints.yaml, library/common-test/tests/statefulset/metadata_test.yaml, library/common/Chart.yaml, library/common/templates/class/_cronjob.tpl, library/common/templates/class/_daemonset.tpl, library/common/templates/class/_deployment.tpl, library/common/templates/class/_job.tpl, library/common/templates/class/_statefulset.tpl, library/common/templates/lib/ingress/integrations/_homepage.tpl, library/common/templates/lib/metadata/_podLabels.tpl
=> chore(labels): adds pod.lifecycle label to pod labels

library/common-test/tests/ingress/homepage_test.yaml, library/common/Chart.yaml, library/common/templates/lib/ingress/integrations/_homepage.tpl
=> fix(homepage): don't render empty keys

library/common-test/tests/rbac/data_test.yaml, library/common-test/tests/rbac/validation_test.yaml, library/common/Chart.yaml, library/common/templates/lib/rbac/_rules.tpl
=> fix(rbac): adds resourceNames

library/common-test/tests/cnpg/stop_test.yaml, library/common-test/tests/container/volumeMounts_test.yaml, library/common-test/tests/ingress/rules_test.yaml, library/common-test/tests/ingress/stop_test.yaml, library/common-test/tests/service/stop_test.yaml, library/common-test/tests/veleroBackupStorageLocation/spec_test.yaml, library/common-test/tests/veleroVolumeSnapshotLocation/spec_test.yaml, library/common/Chart.yaml, library/common/templates/class/velero/_backupStorageLocation.tpl, library/common/templates/class/velero/_volumeSnapshotLocation.tpl, library/common/templates/lib/container/_securityContext.tpl, library/common/templates/lib/container/_volumeMounts.tpl, library/common/templates/lib/ingress/_serviceData.tpl, library/common/templates/lib/pod/_podSecurityContext.tpl, library/common/templates/lib/pod/_volumes.tpl, library/common/templates/lib/storage/_volumeClaimTemplates.tpl, library/common/templates/lib/util/_stopAll.tpl
=> fix(persistence): respect tpl enabled in all places

library/common-test/tests/ingress/stop_test.yaml, library/common-test/tests/service/validation_test.yaml, library/common/Chart.yaml, library/common/templates/class/_endpointSlice.tpl, library/common/templates/class/_ingress.tpl
=> chore(ingress): remove homepage annotations when stopAll is checked

library/common-test/Chart.yaml, library/common-test/tests/ingress/traefik_test.yaml, library/common/Chart.yaml, library/common/templates/lib/ingress/integrations/_traefik.tpl, library/common/values.yaml
=> feat: enable forceTLS on traefik integration on main ingress by default

library/common-test/tests/addons/autoperms_test.yaml, library/common-test/tests/ingress/stop_test.yaml, library/common/Chart.yaml, library/common/templates/class/_ingress.tpl, library/common/templates/lib/util/_autoperms.tpl
=> fix(ingress): explicitly set iCN to null

.github/workflows/common_library_tests.yaml, library/common-test/ci/autopermissions-values.yaml, library/common-test/ci/init-values.yaml, library/common-test/ci/persistence-values.yaml, library/common/values.yaml
=> chore(tests): fix image reference in ci tests

README.md
=> Fixed a tiny typo 

library/common-test/tests/cnpg/credentials_test.yaml, library/common/Chart.yaml, library/common/templates/lib/cnpg/_dbCredentialSecrets.tpl, library/common/templates/lib/dependencies/_dbWait.tpl
=> feat(cnpg): add pooler urls to the secret

library/common-test/tests/cnpg/credentials_test.yaml, library/common/Chart.yaml, library/common/templates/lib/cnpg/_dbCredentialSecrets.tpl
=> chore(cnpg-pooler): use always the pooler url(s)

library/common-test/ci/cnpg-multi-values.yaml, library/common-test/ci/cnpg-values.yaml, library/common/Chart.yaml, library/common/templates/lib/dependencies/_dbWait.tpl
=> chore(cnpg): update key name for RO pooler

library/common/Chart.yaml, library/common/values.yaml
=> chore(common): add yqimage

library/common/Chart.yaml, library/common/templates/lib/chart/_names.tpl
⚒️ Fixes  # 
The FQDN generator was not taking into account a custom chart name.
This fixes it.
**📃 Notes:**
---
=> fix(fqdn): fix fqdn generation

library/common-test/tests/lists/veleroVolumeSnapshotLocationList_test.yaml, library/common-test/tests/lists/volumeScheduleList_test.yaml, library/common-test/tests/secret/data_test.yaml, library/common-test/tests/secret/validation_test.yaml, library/common-test/tests/veleroSchedule/names_test.yaml, library/common-test/tests/veleroSchedule/spec_test.yaml, library/common-test/tests/veleroVolumeSnapshotLocation/metadata_test.yaml, library/common-test/tests/veleroVolumeSnapshotLocation/names_test.yaml, library/common-test/tests/veleroVolumeSnapshotLocation/spec_test.yaml, library/common/Chart.yaml, library/common/templates/class/velero/_schedule.tpl, library/common/templates/class/velero/_volumeSnapshotLocation.tpl, library/common/templates/lib/secret/_validation.tpl, library/common/templates/lib/util/_expandName.tpl, library/common/templates/lib/velero/_providerSecret.tpl, library/common/templates/lib/velero/_volumeSnapshotLocationValidation.tpl, library/common/templates/spawner/velero/_schedule.tpl, library/common/templates/spawner/velero/_volumeSnapshotLocation.tpl
=> chore(common): fix tests and cleanup

library/common-test/tests/persistence/validation_test.yaml, library/common-test/tests/pod/volume_projected_test.yaml, library/common/Chart.yaml, library/common/templates/lib/pod/volumes/_projected.tpl, library/common/templates/lib/storage/_validation.tpl
=> fix(projected): projected volumes fix and tests

library/common-test/tests/pod/runtime_class_name_test.yaml, library/common/Chart.yaml, library/common/templates/lib/pod/_runtimeClassName.tpl
=> fix(gpu): only set nvifia runtime on sclae when nvidia is selected

library/common-test/Chart.yaml, library/common/Chart.yaml, library/common/templates/lib/cnpg/barmanObjectStore/_azure.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_google.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_s3.tpl, library/common/values.yaml
recovery and backup need seperate serverNames.
We make this easy using a user-setable revision, but also will allow for custom servernames
**📃 Notes:**
---
=> feat(cnpg): allow for backup revisions and setting serverName

library/common-test/tests/cnpg/cluster_backup_spec_test.yaml, library/common-test/tests/cnpg/cluster_recovery_spec_test.yaml, library/common-test/tests/cnpg/cluster_spec_test.yaml, library/common-test/tests/cnpg/cluster_validation_test.yaml, library/common-test/tests/service/metadata_test.yaml, library/common-test/tests/volumeClaimTemplate/vct_data_test.yaml, library/common/Chart.yaml, library/common/templates/class/cnpg/_cluster.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_azure.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_getData.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_google.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_s3.tpl, library/common/templates/lib/cnpg/cluster/_boostrapRecovery.tpl, library/common/templates/lib/cnpg/cluster/_bootstrapRecoveryExternalCluster.tpl, library/common/templates/lib/cnpg/cluster/_bootstrapStandalone.tpl, library/common/templates/lib/cnpg/cluster/_validation.tpl, library/common/templates/lib/service/_additionalAnnotations.tpl, library/common/templates/lib/storage/_volumeClaimTemplates.tpl
=> fix(cnpg,accessModes,tests): fix minor bugs and back them with tests

library/common-test/tests/ingress/rules_test.yaml, library/common-test/tests/ingress/validation_test.yaml, library/common/Chart.yaml, library/common/templates/class/_ingress.tpl, library/common/templates/lib/ingress/_validation.tpl
⚒️ Fixes  #735
**📃 Notes:**
---
=> chore(ingress): set default path

library/common-test/tests/ingress/rules_test.yaml, library/common-test/tests/ingress/validation_test.yaml, library/common/Chart.yaml, library/common/templates/class/_ingress.tpl, library/common/templates/lib/ingress/_validation.tpl
=> chore(ingress): set default path (#738)

library/common-test/tests/pod/volume_pvc_test.yaml, library/common/Chart.yaml, library/common/templates/lib/pod/_volumes.tpl
⚒️ Fixes  #734
**📃 Notes:**
---
=> chore(volumes): do not allow RWO vols on daemonsets

library/common-test/tests/ingress/traefik_test.yaml
⚒️ Fixes  # 
Adds a test for https://github.com/truecharts/charts/issues/18448
**📃 Notes:**
---
=> chore(tests): add traefik integration test for svc + ing lists

library/common-test/tests/cnpg/backup_name_test.yaml, library/common-test/tests/cnpg/backup_provider_secret_spec_test.yaml, library/common-test/tests/cnpg/cluster_backup_spec_test.yaml, library/common-test/tests/cnpg/cluster_metadata_test.yaml, library/common-test/tests/cnpg/cluster_name_test.yaml, library/common-test/tests/cnpg/cluster_recovery_spec_test.yaml, library/common-test/tests/cnpg/cluster_spec_test.yaml, library/common-test/tests/cnpg/credentials_test.yaml, library/common-test/tests/cnpg/db_wait_test.yaml, library/common-test/tests/cnpg/pg_version_configmap_test.yaml, library/common-test/tests/cnpg/pooler_metadata_test.yaml, library/common-test/tests/cnpg/pooler_name_test.yaml, library/common-test/tests/cnpg/pooler_spec_test.yaml, library/common-test/tests/cnpg/pooler_validation_test.yaml, library/common-test/tests/cnpg/scheduled_backup_name_test.yaml, library/common-test/tests/cnpg/stop_test.yaml, library/common/templates/lib/cnpg/_dbCredentialSecrets.tpl, library/common/templates/lib/dependencies/_dbWait.tpl, library/common/templates/spawner/_cnpg.tpl, library/common/values.yaml
⚒️ Fixes  # 
Re-applies this https://github.com/truecharts/library-charts/commit/988d82f668e91274ace8a35b0f6dc8b16dde20eb
**📃 Notes:**
---
=> chore(cnpg-pooler): re-apply the pooler urls

library/common-test/Chart.yaml, library/common-test/tests/cnpg/cluster_spec_test.yaml, library/common-test/tests/persistence/pvc_data_test.yaml, library/common-test/tests/pod/volume_pvc_test.yaml, library/common-test/tests/volumeClaimTemplate/vct_data_test.yaml, library/common/Chart.yaml, library/common/templates/class/_persistentVolume.tpl, library/common/templates/class/_pvc.tpl, library/common/templates/class/_service.tpl, library/common/templates/class/cnpg/_cluster.tpl, library/common/templates/lib/container/_ports.tpl, library/common/templates/lib/container/_probes.tpl, library/common/templates/lib/endpoint/_ports.tpl, library/common/templates/lib/endpointSlice/_ports.tpl, library/common/templates/lib/pod/_volumes.tpl, library/common/templates/lib/service/_ports.tpl, library/common/templates/lib/storage/_accessModes.tpl, library/common/templates/lib/storage/_storageClassName.tpl, library/common/templates/lib/storage/_volumeClaimTemplates.tpl, library/common/templates/lib/storage/pvc/_name.tpl, library/common/templates/lib/storage/pvc/_spec.tpl, library/common/templates/lib/util/_autoperms.tpl, library/common/templates/spawner/_cnpg.tpl, library/common/templates/spawner/_pvc.tpl, library/common/values.yaml
Does what it says on the tin
Fixes: #727
**📃 Notes:**
---
=> feat(common): move fallbackDefaults to global section

library/common-test/ci/statefulset-values.yaml, library/common-test/tests/addons/autoperms_test.yaml, library/common-test/tests/container/volumeMounts_test.yaml, library/common-test/tests/defaults/enabled_test.yaml, library/common-test/tests/volumeClaimTemplate/names_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_volumeMounts.tpl, library/common/templates/lib/pod/_containerSpawner.tpl, library/common/templates/lib/pod/_initContainerSpawner.tpl, library/common/templates/lib/util/_enabled.tpl, library/common/templates/values/lists/_serviceList.tpl
⚒️ Fixes  #728
**📃 Notes:**
---
=> chore(enabled): make sure the key always exist

library/common-test/tests/cnpg/cluster_spec_test.yaml, library/common-test/tests/cnpg/pg_version_configmap_test.yaml, library/common-test/tests/workload/validation_test.yaml, library/common/templates/lib/metadata/_namespace.tpl
=> chore(tests): backfill tests

library/common/Chart.yaml, library/common/templates/lib/storage/_storageClassName.tpl
=> fix(sc): fix sc lookup

library/common-test/tests/container/resources_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_resources.tpl, library/common/templates/lib/dependencies/_dbWait.tpl
=> chore(resources): limit resources on init containers

library/common-test/tests/container/resources_test.yaml, library/common/templates/class/cnpg/_cluster.tpl
=> fix(resources): also exclude cnpg containers from getting the extra resources

library/common-test/tests/storageClass/metadata_test.yaml, library/common-test/tests/storageClass/spec_test.yaml, library/common/Chart.yaml, library/common/templates/class/_storageClass.tpl, library/common/templates/lib/storage/_storageClassValidation.tpl
=> fix(storageClass): fix storage class and add tests

library/common-test/tests/pod/topologySpreadConstraints.yaml
⚒️ Fixes  # 
228e8c0595676c302069885a636a1fdead2941df
**📃 Notes:**
---
=> chore(tests): fix tests

library/common-test/tests/container/probes_test.yaml, library/common/Chart.yaml, library/common/templates/lib/container/_probes.tpl, library/common/templates/lib/util/_diagnoseMode.tpl, library/common/templates/lib/util/_diagnosticMode.tpl, library/common/values.yaml
⚒️ Fixes  #788
**📃 Notes:**
---
=> chore(diagnostic): add diagnostic mode

.github/workflows/common.release.yaml, .github/workflows/common_library_tests.yaml, library/common-test/tests/rbac/data_test.yaml, library/common-test/tests/rbac/validation_test.yaml, library/common/Chart.yaml, library/common/templates/lib/rbac/_rules.tpl
Some applications do need this.
**📃 Notes:**
---
=> feat(common): add support for RBAC nonResourceURLs

library/common-test/tests/cnpg/cluster_recovery_spec_test.yaml, library/common/Chart.yaml, library/common/templates/lib/cnpg/barmanObjectStore/_azure.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_google.tpl, library/common/templates/lib/cnpg/barmanObjectStore/_s3.tpl, library/common/templates/spawner/_pvc.tpl, library/common/values.yaml
We want volsync and cnpg to be well integrated when writhing backups to s3.
While we also want to prevent potential conflicts
**📃 Notes:**
---
=> feat: adapt cnpg/volsync Backup pathing

library/common/Chart.yaml, library/common/templates/class/volsync/_replicationDestination.tpl, library/common/templates/lib/volsync/_storage.tpl
So lets just always supply the set accessmodes.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix: volsync requires accessModes in some cases

.github/workflows/common_library_tests.yaml, library/common-test/tests/ingress/traefik_test.yaml
=> chore(traefik): add test for lookup

library/common-test/tests/cnpg/cluster_recovery_spec_test.yaml, library/common-test/tests/cnpg/cluster_spec_test.yaml, library/common-test/tests/lists/credentialsList_test.yaml, library/common-test/tests/volsync/replication_dest_spec_test.yaml, library/common-test/tests/volsync/validation_test.yaml, library/common/Chart.yaml, library/common/templates/class/volsync/_replicationDestination.tpl, library/common/templates/lib/credentials/_validation.tpl
=> fix(tests): fix flaky tests from updates

library/common-test/tests/volsync/replication_dest_spec_test.yaml, library/common-test/tests/volsync/replication_src_spec_test.yaml, library/common/Chart.yaml, library/common/templates/lib/volsync/_storage.tpl
Primarily aims to expand coverage for stageclassname and volumesnapshotclassname
⚒️ Fixes  # 
**📃 Notes:**
---
=> chore(volsync): increase test coverage for specific usecases

library/common-test/tests/pod/host_users_test.yaml, library/common-test/tests/pod/node_selector_test.yaml, library/common/Chart.yaml, library/common/templates/lib/pod/_hostUsers.tpl, library/common/templates/lib/pod/_nodeSelector.tpl, library/common/values.yaml
⚒️ Fixes  #823 
⚒️ Partially #826 
**📃 Notes:**
---
=> fix(nodeSelector, hostUsers): make sure booleans are quoted, respect user defined value over automatic calculation

library/common-test/tests/cnpg/credentials_test.yaml, library/common/Chart.yaml, library/common/templates/lib/cnpg/providers/_providerSecretSpawner.tpl, library/common/templates/lib/ingress/integrations/_traefik.tpl
⚒️ Fixes  #813
**📃 Notes:**
---
=> chore(credentials): expand checks

library/common/Chart.yaml, library/common/templates/lib/chart/_check_capabitilies.tpl
⚒️ Fixes  #829 
https://helm.sh/docs/chart_template_guide/function_list/#semantic-version-functions
**📃 Notes:**
---
=> fix(checks): fix helm version check

library/common-test/tests/podDisruptionBudget/spec_test.yaml, library/common-test/tests/podDisruptionBudget/validation_test.yaml, library/common/Chart.yaml, library/common/templates/lib/podDistruptionBudget/_validation.tpl
=> chore(pdb): expand tests

library/common-test/tests/chartContext/portal_test.yaml, library/common/Chart.yaml, library/common/templates/spawner/_portal.tpl
=> fix(portal): fix name and tests
