charts/common/Chart.yaml
charts/common/templates/lib/utils/_storage.tpl
helper-charts/common-test/ci/persistence-values.yaml

There where a number of issues where the wrong storageClass might've been rendered.
Mostly due to the fact that storageClassName can be either `null` or `""` or `value`, each of which having a different meaning.
**📃 Notes:**

Fix storageClassBugs

---

charts/common/templates/classes/_ingress.tpl

When deploying an app with an ingressClassName, the middleware namespace is always `default` instead of using the namespace of the middleware 
⚒️ Fixes  #55 
I have tested with a blank chart that changing `:=` to `=` allows the value to be changed away from `"default"`.
**📃 Notes:**
It is not clear to me how I would go about doing an integration test for this fix

Fix ingressClassName middleware namespacing

---

charts/common/Chart.yaml
charts/common/templates/class/_service.tpl

⚒️ Fixes  https://github.com/truecharts/apps/issues/2935
**📃 Notes:**

fix(service): don't set ipFamilyPolicy when svc is ExternalName

---

charts/common/Chart.yaml
charts/common/templates/lib/dependencies/_clickhouseInjector.tpl
helper-charts/common-test/tests/persistence/volumeclaimtemplates_test.yaml

I accidentally applied `b64enc` to `values.yaml` and not only the data of the k8s secret.
⚒️ Fixes  # 
**📃 Notes:**
---

Don't `b64enc` ClickHouse values

---

.github/workflows/charts-lint-test.yaml
charts/common/Chart.yaml
charts/common/templates/lib/controller/_prepare.tpl
charts/common/templates/lib/util/_manifest-updater.tpl
charts/common/values.yaml
helper-charts/common-test/tests/pod/initcontainers_test.yaml
helper-charts/common-test/tests/pod/installcontainers_test.yaml
helper-charts/common-test/tests/pod/upgradecontainers_test.yaml

This PR splits the root-requiring and non-root-requiring parts of the default initcontainer.
- The root-requiring part, is now run on a bare-bones alpine image, for added security.
- The database waits, are now running rootless.
In the future more of the initcontainers should be hardened with least-privilage in mine.
**📃 Notes:**
---

feat(common): allow for rootless db-wait and cve-free autopermissions

---

library/common-test/Chart.yaml
library/common/Chart.yaml
library/common/templates/class/_cnpgCluster.tpl
library/common/templates/spawner/_cnpg.tpl

Add functionality to migrate old postgresql databases to cnpg.
This is not guaranteed(!) to work for every app and every database, but it offers a semi-decent option to at least TRY to migrate, instead of forcing users to do this manually
**📃 Notes:**
See:
https://cloudnative-pg.io/documentation/1.18/bootstrap/
---

feat(common): allow postgres -> cnpg migration

---

library/common/Chart.yaml
library/common/templates/lib/container/_env.tpl
library/common/templates/lib/container/_envFrom.tpl
library/common/templates/spawner/_configmap.tpl
library/common/templates/spawner/_secret.tpl

This fixes some issues where secrets/configmaps couldn't be dynamicly be disabled or could env references be dynamically switch between expanded and non-expanded object names
**📃 Notes:**
---

feat(common): allow tpl for env expandObjectName, configmap-name and secret-name

---

library/common-test/tests/cnpg/custom_conf_test.yaml
library/common/Chart.yaml
library/common/templates/class/_cnpgCluster.tpl
library/common/values.yaml

As requested by @stavros-k allow custom postgresql config on a per-chart basis
**📃 Notes:**
---

feat(cnpg): add postgresql section for custom config

---

library/common/Chart.yaml
library/common/templates/class/_statefulset.tpl
library/common/templates/lib/storage/_volumeClaimTemplates.tpl

rename vct file according to file location and don't load standard labels and annotations for vct to prevent failure cases
⚒️ Fixes  # 
**📃 Notes:**
---

Fix VCT issues

---

library/common/Chart.yaml
library/common/templates/lib/service/serviceTypeSpecs/_loadBalancer.tpl

The default setting is enabled, which causes SEVERE security concerns, exposing apps on random ports for everyone to exploit.
WTF.
**📃 Notes:**
---

fix(common): prevent random nodePorts being assigned for LoadBalancer

---

library/common-test/Chart.yaml
library/common/Chart.yaml
library/common/templates/lib/util/_chartcontext.tpl
library/common/templates/loader/_init.tpl
library/common/templates/spawner/_portal.tpl
library/common/values.yaml

We need our own chartContext available with things like an application url (taking LB and ingress into account) and potential place to save CIDR info in a platform agnostic way
**📃 Notes:**
---

feat(common): Add Chartcontext for appurl and cidrs

---

library/common-test/tests/container/securityContext_test.yaml
library/common/Chart.yaml
library/common/templates/lib/container/_securityContext.tpl
library/common/values.yaml

S6 overlay needs some more caps it looks like.
And with the growth of caps we should also bundle them in one disable toggle.
**📃 Notes:**
---

fix(common): allow for more caps when running as root and bundle the disable

---

library/common/Chart.yaml
library/common/templates/addons/vpn/_gluetunContainer.tpl
library/common/templates/addons/vpn/_openvpnContainer.tpl
library/common/templates/addons/vpn/_wireguardContainer.tpl

- Allows the killswitch to be used on Gluetun
- Disable most of the GlueTun DNS settings
- Adds dynamic auto-whitelisted CIDR's (cluster CIDR's) based on chartContext for GlueTun and Wireguard
- Cleans up some of the VPN provider code
**📃 Notes:**
---

fix(gluetun):  gluetun killswitch,disable GlueTun DNS and dynamic gluetun/wireguard cidr whitelist

---

library/common-test/tests/service/external_ip_test.yaml
library/common/Chart.yaml
library/common/templates/lib/endpointSlice/_ports.tpl

⚒️ Fixes  # 
EndpointSlice's `port` must point to the port the server is listenting (the same port Service's targetPort is pointing)
TL;DR Service's `targetPort` + EndpointSlice's `port` must match
https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors
**📃 Notes:**
---

Revert a fix for endpointslice

---

library/common-test/tests/persistence/pvc_data_test.yaml
library/common/Chart.yaml
library/common/templates/lib/util/_manifest_manager.tpl
library/common/values.yaml

⚒️ Fixes  https://github.com/truecharts/charts/issues/8382
**📃 Notes:**
---

fix(manifestManager): Handle failed/completed pods before waiting for the Ready pods + increase deafult pvc size

---

library/common-test/tests/addons/codeserver_test.yaml
library/common/Chart.yaml
library/common/templates/lib/container/_volumeMounts.tpl

⚒️ Fixes  https://github.com/truecharts/charts/issues/8694
When there is a `targetSelector` defined, don't try to mount this volume to codeserver. As it's most likely a configmap/secret or a volume only relevant to a specific container
eg:
```yaml
persistence:
init:
enabled: true
type: configmap
objectName: init
mountPath: "/config/init"
defaultMode: "0777"
readOnly: true
targetSelector:
main:
init: {}
```
But the caveat is that also this wont be mounted:
```yaml
persistence:
vol:
enabled: true
type: emptyDir
mountPath: "/config/init"
targetSelector:
main:
main: {}
```
TL;DR only volumes without a selector or a selector with `targetSelectAll` will be mounted to codeserver.
Not sure what we could do on scale GUI to make this more flexible. Needs more thought.
But this is a …

fix(codeserver): don't try to mount a volume if it's target on a specific container

---

.github/workflows/common_library_tests.yaml
library/common/Chart.yaml
library/common/templates/lib/container/_probes.tpl
library/common/templates/lib/container/_securityContext.tpl
library/common/templates/lib/pod/_tolerations.tpl
library/common/templates/lib/service/serviceTypeConfig/_sessionAffinity.tpl

⚒️ Fixes  # 
Looks like when using `--set`, numbers are passed as int64.. lets accept that type too
https://discord.com/channels/830763548678291466/1084773448921907200/1106307442884755478
**📃 Notes:**
---

fix(checks): accept int64 as a valid int type

---

library/common-test/Chart.yaml
library/common/Chart.yaml
library/common/templates/class/_cnpgCluster.tpl
library/common/templates/class/_cnpgPooler.tpl
library/common/values.yaml

cluster hibernation is a good way to get CNPG to scale down to 0 cleanly.
This might(!) be a potential solution for fixing the broken stop button on SCALE as well, but that's not fully clear as of yet.
This also scales down the poolers to 0 as well. To ensure nothing remains active.
**📃 Notes:**
---

feat(common): add support for cnpg cluster hibernation without using annotations

---

library/common-test/Chart.yaml
library/common/Chart.yaml
library/common/templates/class/_cnpgCluster.tpl
library/common/templates/class/_cnpgPooler.tpl
library/common/templates/lib/pod/_nodeSelector.tpl
library/common/templates/lib/workload/_cronjobSpec.tpl
library/common/templates/lib/workload/_deployementSpec.tpl
library/common/templates/lib/workload/_jobSpec.tpl
library/common/templates/lib/workload/_statefulsettSpec.tpl
library/common/values.yaml

This implements a SCALE stop-button *like* experience on native helm.
This one actually works, in stark contrast to the iX stop-button attempt:
- It uses helm, so helm edits don't magically start apps again (iX stop button messes with objects managed by helm)
- It actually stops daemonsets (by only scheduling them on non-existing nodes)
- It actually prevents (cron)jobs from running
- It hibernates cnpg clusters
- It can be expanded to as many custom objects as wel like/need in the future
**📃 Notes:**
Can be abstracted away a bit (by putting an include in-between) to also stop things prior to using the SCALE stop button, when iX ever exposes that option.
If this PR is an app addition …

feat(common): Add .global.stopAll option to stop all on native Helm

---

library/common-test/tests/pod/securityContext.yaml
library/common/Chart.yaml
library/common/templates/lib/pod/_podSecurityContext.tpl

⚒️ Fixes  # 
If `net.ipv4.ip_unprivileged_port_start` is set and hostNet is enabled k8s throw an error that is not supported combination
**📃 Notes:**
---

fix(sysctls): dont add net.ipv4.ip_unprivileged_port_start when hostNet is enabled

---

.github/workflows/common_library_tests.yaml
library/common-test/Chart.yaml
library/common-test/ci/register-operator-values.yaml
library/common-test/default-values.yaml
library/common-test/tests/addons/codeserver_test.yaml
library/common-test/tests/addons/netshoot_test.yaml
library/common-test/tests/addons/vpn_test.yaml
library/common-test/tests/configmap/metadata_test.yaml
library/common-test/tests/defaults/defaults-test.yaml
library/common-test/tests/operator/operator_test.yaml
library/common-test/tests/secret/metadata_test.yaml
library/common-test/values.yaml
library/common/Chart.yaml
library/common/templates/class/_configmap.tpl
library/common/templates/class/_secret.tpl
library/common/templates/lib/util/_register_operator.tpl
library/common/templates/lib/util/_tc_namespace.tpl
library/common/templates/lib/util/_tcnamespace.tpl
library/common/templates/lib/util/_verify_operator.tpl
library/common/templates/loader/_init.tpl
library/common/values.yaml

We got requests from iX that they would like us to not side-load operators into namespaces that are not SCALE managed.
This feature limits allows us to use dynamically named namespaces for charts containing operators.
It registers all operators and their namespace using a configmap in the fixed `tc-system` namespace.
This means all operators can use dynamic namespaces (if the operator itself supports that) and don't have to be hotloaded in non-scale namespaces by manifestmanager in the future anymore.
It also moves tc-system namespace creation to common.
This ensures we can also change traefik middleware namespace logic later as well.
On top of this, it also contains logic to prevent duplicate installs of the same operator.
**🧪 How Has This Been …

feat(common): implement support for registering and verifying dynamic operator namespaces

---

library/common-test/ci/register-operator-values.yaml
library/common/Chart.yaml
library/common/templates/lib/util/_manifest_manager.tpl
library/common/values.yaml

This PR reenables manifest manager by default and creates additional toggles for both install and checks.
It also, more importantly, adds an option to delete resources created using manifestmanager, a prerequisite for moving to building our own operator helm-charts
**📃 Notes:**
---

fix(common): reenable manifest manager and add deletion logic

---

library/common-test/tests/pod/volume_device_test.yaml
library/common/templates/lib/pod/volumes/_device.tpl

⚒️ Fixes  # 
When someone tries to mount a device from host that does not exist, k8s will create a *directory* (on the host) in it's place
That means that when they actually plug the usb it will still be a directory unless manually fixed.
So when we detect one of those devices, lets set its hostPathType to avoid that.
We can extend the "filter" list once we figure out more things
**📃 Notes:**
---

fix(devices): set the hostPathType when a hostPath matches some criteria

---

library/common/Chart.yaml
library/common/templates/lib/util/_verify_operator.tpl
library/common/values.yaml

This PR enabled operator validation failing with an error when operators are not found.
This means users actually will **need** to migrate to the new way of handling operators.
**📃 Notes:**
---

chore(common): hardfail with clear error when required operators are not found.

---

library/common-test/tests/imagePullSecret/data_test.yaml
library/common/templates/lib/imagePullSecret/_createData.tpl

⚒️ Fixes  #520
```shell
helm unittest -f tests/imagePullSecret/data_test.yaml library/common-test
```
**📃 Notes:**

fix: imagePullSecret registry value

---

library/common-test/tests/certificate/validation_test.yaml
library/common-test/tests/configmap/validation_test.yaml
library/common-test/tests/imagePullSecret/validation_test.yaml
library/common-test/tests/secret/validation_test.yaml
library/common/Chart.yaml
library/common/templates/lib/chart/_names.tpl
library/common/templates/spawner/_configmap.tpl
library/common/templates/spawner/_imagePullSecret.tpl
library/common/templates/spawner/_portal.tpl
library/common/templates/spawner/_scaleCertificate.tpl
library/common/templates/spawner/_secret.tpl

fix(name-checks): allow 253 chars in configmap/secrets

---

library/common/templates/class/_certificate.tpl
library/common/templates/spawner/_certificate.tpl

Adds the ability to add `secretTemplate` property to Certificate CRDs.
Related to: https://github.com/truecharts/charts/issues/8634
⚒️ Fixes  # 
Haven't explicitly tested it. See Notes.
**📃 Notes:**
Not sure how I can test the lib. I hope this is a simple enough change that doesn't need testing before merging.
---

feat(certificates): Add secretTemplate to certificate CRD

---

library/common-test/Chart.yaml
library/common/Chart.yaml
library/common/templates/class/_ingress.tpl
library/common/templates/loader/_lists.tpl
library/common/templates/spawner/_certificate.tpl
library/common/templates/values/lists/_ingressList.tpl

- Changes the name of certificates with a secrettemplate, to make it easier to use kubernetes-reflector and ingress on those, ensures they do not include the fullname namespace of the chart creating the certificate
- readds a parser for ingressList, not sure if functional, but at least it exists on a basic level now
- Adds the ability to define clusterCertificates on ingress.tls and automatically fix/apply the secrettemplate naming scheme accordingly.
**📃 Notes:**
---
Those checkboxes are there for the reviewer to see what …

feat(common): add support for clusterCertificate to ingress and readd ingresslist

---

library/common-test/Chart.yaml
library/common-test/tests/pod/node_selector_test.yaml
library/common-test/tests/pod/topologySpreadConstraints.yaml
library/common/Chart.yaml
library/common/templates/lib/pod/_nodeSelector.tpl
library/common/templates/lib/pod/_topologySpreadConstraints .tpl
library/common/templates/lib/workload/_pod.tpl
library/common/values.yaml

When moving to support clustered and multi-arch systems, we need to ensure our charts are only ran on AMD64 by default, as not all containers support ARM64 (or example).
Further more, we need to ensure our pods can have their topologySpreadConstraints set.
As replica's of the same deployment, should not be put on the same nodes and, preferably, spread accross multiple racks (failure domains), we need to setup sane defaults to push the kubernetes scheduler to try to put replica's on seperate nodes and failure domains by default for Deployments and StatefulSets.
**📃 Notes:**
Also removes the failure on empty nodeSelector and instead skips empty nodeSelectors, this allows for explicit overrides.
**➕ App …

feat(common): limit default arch to AMD64, add topologySpreadConstraints and ensure solid default spread

---

library/common/Chart.yaml
library/common/templates/lib/util/_primary_certificate.tpl

Older helm versions, such as TrueNAS SCALE Bluefin, throw an error due to missing primary cert util object.
This adds said object
**📃 Notes:**
---

fix(common): fix primary cert warning on older helm versions

---

library/common-test/Chart.yaml
library/common-test/ci/priorityclass-values.yaml
library/common-test/tests/pod/priority_class_name_test.yaml
library/common-test/tests/priorityClass/metadata_test.yaml
library/common-test/tests/priorityClass/names_test.yaml
library/common-test/tests/priorityClass/spec_test.yaml
library/common/Chart.yaml
library/common/templates/class/_priorityClass.tpl
library/common/templates/lib/priorityClass/_validation.tpl
library/common/templates/loader/_apply.tpl
library/common/templates/spawner/_priorityClass.tpl
library/common/values.yaml

This adds the ability to spawn priorityClass objects using common.
In the future we might want to use this to set some standardised priorityClasses to correct/improve scheduling of our charts
⚒️ Fixes  # 
**📃 Notes:**
---

feat(common): add priorityClass class and spawner

---

library/common-test/tests/addons/autoperms_test.yaml
library/common-test/tests/defaults/defaults-test.yaml
library/common/Chart.yaml
library/common/values.yaml

This should limit the iops saturation of certain apps a bit
⚒️ Fixes  #601
**📃 Notes:**
---

fix(common): default /tmp and /var/logs to memory emptyDirtype

---

library/common-test/tests/persistence/validation_test.yaml
library/common-test/tests/pod/volume_iscsi_test.yaml
library/common/templates/lib/pod/_volumes.tpl
library/common/templates/lib/pod/volumes/_iscsi.tpl
library/common/templates/lib/storage/_iscsiChap.tpl
library/common/templates/lib/storage/_validation.tpl
library/common/templates/spawner/_pvc.tpl
library/common/values.yaml

Besides nfs, we can also allow mounting of iscsi volumes directly to pods.
Which should allow users more flexibility for using their prefered storage, primarily because it's also easy to implement in TrueNAS SCALE
⚒️ Fixes  #592
**📃 Notes:**
---

feat(common): add support for iscsi volumes

---

library/common-test/tests/addons/autoperms_test.yaml
library/common-test/tests/defaults/defaults-test.yaml
library/common-test/tests/pod/volume_emptyDIr_test.yaml
library/common/Chart.yaml
library/common/templates/lib/pod/volumes/_emptyDir.tpl

Currently emptyDir ramdisks are set to have unlimited size.
This puts a limit to that, sized in accordance to .values.resources.limits.memory
Yes this means an App consuming all space in an emptyDir can exceed the limits, but at least it prevents attacks where host OOMs can be triggered by oversaturating a memory-backed emptyDir
⚒️ Fixes  #602 
**📃 Notes:**
---

fix(common): limit default emptydir size for memory emptyDir

---

library/common-test/Chart.yaml
library/common-test/tests/imagePullSecret/data_test.yaml
library/common-test/tests/imagePullSecret/name_test.yaml
library/common/Chart.yaml
library/common/templates/loader/_lists.tpl
library/common/templates/values/lists/_imagePullSecretList.tpl
library/common/values.yaml

On scale it would be best to render imagePullSecrets as a list in the GUI
⚒️ Fixes  #600
**📃 Notes:**
---

feat(common): allow for imagePullSecrets to be input in a list for scale GUI

---

library/common-test/tests/persistence/pvc_with_snapshot.yaml
library/common-test/tests/priorityClass/metadata_test.yaml
library/common-test/tests/priorityClass/spec_test.yaml
library/common-test/tests/storageClass/metadata_test.yaml
library/common-test/tests/storageClass/spec_test.yaml
library/common-test/tests/volumeSnapshot/metadata_test.yaml
library/common-test/tests/volumeSnapshot/names_test.yaml
library/common-test/tests/volumeSnapshot/spec_test.yaml
library/common/templates/class/_volumeSnapshot.tpl
library/common/templates/lib/storage/_validationVolumeSnapshot.tpl
library/common/templates/loader/_apply.tpl
library/common/templates/spawner/_pvc.tpl
library/common/templates/spawner/_volumeSnapshot.tpl
library/common/values.yaml

Adds support for adding a list of volumesnapshots to each PVC persistence object.
Also adds a root level volumeSnapshots list for custom volumeSnapshots
⚒️ Fixes  #571
**📃 Notes:**
---

feat(common): add support for defining a list of volumeSnapshots

---

library/common/templates/addons/code-server/_codeserver.tpl
library/common/templates/lib/util/_verify_operator.tpl

The codeserver ingress uses a non existent include to get the fullname. It also does not set a name for the ingress, causing the resulting ingress resource have no name which kubernetes does not accept. It also uses the wrong namespace for middleware when no other regular ingresses are configured due to the operator verification only checking `.Values.ingress`.
Applying the fixes locally and running the updated code. The codeserver ingress got deployed without problems and worked perfectly.
**📃 Notes:**
---
Those checkboxes …

fix(common): Bugfixes on codeserver ingress

---

library/common-test/tests/service/load_balancer_test.yaml
library/common-test/tests/service/validation_test.yaml
library/common/Chart.yaml
library/common/templates/lib/service/_additionalAnnotations.tpl
library/common/templates/lib/service/serviceTypeSpecs/_loadBalancer.tpl
library/common/templates/lib/util/_chartcontext.tpl

⚒️ Fixes  # 
https://github.com/kubernetes/kubernetes/pull/107235
```sh
Failed to allocate IP for "ix-blocky/blocky-dot": service can not have both metallb.universe.tf/loadBalancerIPs and svc.Spec.LoadBalancerIP
```
**📃 Notes:**
---

fix(loadbalancerIP): remove loadbalancerIP from service spec and only use annotations

---

library/common-test/tests/ingress/stop_test.yaml
library/common-test/tests/ingress/validation_test.yaml
library/common-test/tests/service/stop_test.yaml
library/common/Chart.yaml
library/common/templates/class/_ingress.tpl
library/common/templates/class/_service.tpl
library/common/templates/lib/ingress/_validation.tpl

Currently ingress and loadbalancer reservations are still being made for stopped charts.
With this change we set services to clusterip, to prevent external connections.
We also set ingress to a special `stopped` ingressClass, this ensures we don't nuke things like certificates when stopping
**📃 Notes:**
---

fix(common): ensure no loadbalancer reservation is made and ingress is not connected to ingresscontroller with Stop-All set

---

library/common-test/tests/ingress/homepage_test.yaml
library/common/Chart.yaml
library/common/templates/lib/ingress/integrations/_homepage.tpl

⚒️ Fixes  #654
**📃 Notes:**
---

fix(homepage integration): use release.name instead of chart.name for homepage name component

---

library/common-test/tests/ingress/homepage_test.yaml
library/common/Chart.yaml
library/common/templates/lib/ingress/integrations/_homepage.tpl

⚒️ Fixes  https://github.com/truecharts/library-charts/issues/653
**📃 Notes:**
---

fix(homepage): allow to disable widget

---

library/common-test/tests/ingress/homepage_test.yaml
library/common/Chart.yaml
library/common/templates/lib/ingress/integrations/_homepage.tpl

⚒️ Fixes  #655
By default when you dont set a selector, homepage uses the appName (from their config) as a selector.
We can set the correct selector there ourselves.
https://github.com/gethomepage/homepage/blob/4d6754e4a7258c46047d3cc2ca2e3fe63f6df76a/src/pages/api/kubernetes/status/%5B...service%5D.js#L19
**📃 Notes:**
---

fix(homepage): fix default selector

---

library/common/Chart.yaml
library/common/templates/class/velero/_backupStorageLocation.tpl
library/common/templates/class/velero/_volumeSnapshotLocation.tpl

Velero still does some validation on config keys, even if the value is empty.
This can cause into issues with invalid keys and such, which should be no issue when empty.
However, scale adds all keys, empty.
**📃 Notes:**
---

fix(velero): only process non-empty keys for config

---

library/common/Chart.yaml
library/common/templates/lib/chart/_check_capabitilies.tpl

⚒️ Fixes  #691
At the time we do the pre-flight checks, the `.Values.global` from common have not yet been merged with the chart values.
So trying to directly access anything under global, will panic.
So, safely access the underlying keys, by checking that global is not empty first.
**📃 Notes:**
---

fix(checks): prevent nil pointer

---

library/common-test/Chart.yaml
library/common-test/ci/schedule-values.yaml
library/common-test/tests/veleroSchedule/spec_test.yaml
library/common/Chart.yaml
library/common/templates/class/velero/_schedule.tpl
library/common/values.yaml

After some discussion, we would prefer to have users setup velero schedules on a per-chart basis, besides any options available on the velero chart itself.
However the schedules need to be installed inside the velero namespace, while the included namespace, should (by default) be limited to the chart itself
**📃 Notes:**
---

feat(common): allow adding velero schedule to individual charts

---

library/common-test/tests/secret/data_test.yaml
library/common-test/tests/secret/validation_test.yaml
library/common/templates/lib/secret/_validation.tpl

These will likely get created with the goal of the kube-system adding data. Not us
**📃 Notes:**
---

fix(common): allow kubernetes.io/service-account-token secrets to not have data

---

.github/workflows/common.release.yaml
.github/workflows/common_library_tests.yaml
library/common-test/Chart.yaml
library/common/Chart.yaml
library/common/templates/lib/pod/_volumes.tpl
library/common/templates/lib/pod/volumes/_projected.tpl

Current common does not support projected volumes.
Which we need to mount serviceaccounttokens as files for https://github.com/truecharts/charts/pull/18259
**📃 Notes:**
---

feat(common): add support for projected Volumes

---

library/common-test/Chart.yaml
library/common-test/tests/container/envFixed_test .yaml
library/common-test/tests/container/resources_test.yaml
library/common-test/tests/initContainer/data_test.yaml
library/common-test/tests/initContainer/data_upgrade_test.yaml
library/common-test/tests/pod/runtime_class_name_test.yaml
library/common/Chart.yaml
library/common/templates/lib/container/_fixedEnv.tpl
library/common/templates/lib/container/_resources.tpl
library/common/templates/lib/pod/_runtimeClassName.tpl

This is an early draft to correctly set the runtimeClass name, when using nvidia GPU on SCALE, but without the SCALE GPU GUI.
**📃 Notes:**
---

feat(common): allow nvidia runtimeclass outside of scaleGPU on SCALE

---

library/common-test/tests/cnpg/cluster_spec_test.yaml
library/common/Chart.yaml
library/common/templates/lib/cnpg/cluster/_bootstrapStandalone.tpl

We should set custom initdb sql, AFTER we've enabled extentions, otherwise we cannot run this SQL over extention specific codepaths
**📃 Notes:**
---

chore(common): change order of initdb init application sql

---

library/common/Chart.yaml
library/common/templates/lib/metadata/_namespace.tpl

Some users are fucking around trying to get kubeapps recognised by SCALE, this is PRECISELY what iX-Systems **and** TrueCharts do **NOT** want. As fucking around with this, **will** lead to inherent issues. Only to have people play dumb and file support tickets at either party
**📃 Notes:**
---

feat(common): prevent the use of `ix-` namespace prefix outside of SCALE-Apps

---

library/common-test/Chart.yaml
library/common-test/tests/persistence/pvc_data_test.yaml
library/common-test/tests/persistence/validation_test.yaml
library/common-test/tests/volumeClaimTemplate/validation_test.yaml
library/common-test/tests/volumeClaimTemplate/vct_data_test.yaml
library/common/Chart.yaml
library/common/templates/lib/storage/_storageClassName.tpl

This is a **TEMPORARY** hotfix to ensure SCALE users that forgot setting their `storageClass` to `SCALE-ZFS`, loose data on update to dragonfish.
This will be removed in the future, likely together with support for SCALE storageClasses all-together.
**📃 Notes:**
---

feat(common): add a temporary failsafe to filter dragonfish and cobia SCALE users that forgot to follow instructions

---

library/common/Chart.yaml
library/common/templates/addons/vpn/_gluetunContainer.tpl

Hello,
right now there is no default definition for FIREWALL_INPUT_PORTS which seem to be needed on helm/kubeapps deployment for healthcheck to work ([see gluetun wiki](https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/firewall.md)). I think if I did this right this will pull main service port from values.yaml and automatically open it on default interface for health check.
note: if service uses multiple ports, this likely wont work for all of them and user will need to manually set FIREWALL_INPUT_PORT themselves.
⚒️ Fixes  # 
i don't know how to test locally, i'm so sorry >.<;;
**📃 Notes:**
--- …

fix(gluetun): add FIREWALL_INPUT_PORTS pointing to main service port

---

library/common/Chart.yaml
library/common/templates/addons/vpn/_gluetunContainer.tpl
library/common/values.yaml

This implement idea by @stavros-k in #771 and also add logic to detect when user has enable qbitportforward, and automatically add gluetun control port to inputPorts as well. Thank you stavros for help!
⚒️ Fixes  # 
**📃 Notes:**
---

feat(gluetun): add inputPorts & handle common usecase

---

library/common/Chart.yaml
library/common/templates/lib/container/_probes.tpl
library/common/values.yaml

There is a design mistake in the probe setup:
Liveness probe:
Stops the container on failure, this should happen AFTER readiness probe detects failure.
Readiness Probe:
Stops the service forwarding traffic. This should happen BEFORE the liveness probe detects failure
Startup Probe:
By having a tcp startup-probe, charts might pass CI when not fully working. or, worse, get passed-over to the readiness/liveness probes when the container is still doing maintenance work (such as plex database updates). Leading to it right-away being thrown-out by liveness/readyness
I also attempted to offset start of liveness and readyness, this ensures they don't send probes at the same time, while making it most-likely that liveness clears before readiness on startup.
While also offsetting …

fix(common): improve probes

---

library/common-test/tests/ingress/traefik_test.yaml
library/common/Chart.yaml
library/common/templates/lib/ingress/integrations/_traefik.tpl
library/common/values.yaml

⚒️ Fixes  https://github.com/truecharts/library-charts/issues/825
Having the `enableFixedMiddlewares` defined by **default** in `main` ingress, will cause the fixed middlewares to always be enabled, even if global is disabled.
Code is structured in a way that will ignore ingress level toggle if the key is missing completely. So the global will take effect.
Note:
It might be breaking for existing users that explicitly disabled fixed middlewares from global, but left the "default" on main.
**📃 Notes:**
---
Those checkboxes are …

fix(traefik): remove enableFixedMiddlewares key from global

---

library/common-test/tests/podDisruptionBudget/spec_test.yaml
library/common/Chart.yaml
library/common/templates/class/_podDisruptionBudget.tpl

Pod Disruption Budgets don't contain a data field but a spec one.
This doesn't cause an error immediately since k8s ignores unknown fields, but renders all existing PDBs useless
as they are not properly configured. 
⚒️ Fixes  # 
Didn't managed to make an issue but went straight to fixing it :)
The existing test suite is good enough I simply modified it to expect a `spec` field rather than a `data` one.
**📃 Notes:**
---
the status of this PR with a …

fix(pdb): Pod Disruption Budgets have spec not data

---

library/common/values.yaml

Currently, both `maxUnavailable` and `minAvailable` are set to `1` in common.yaml. This results in bolt values being set if `PodDisruptionBudget` is enabled in any Helm charts. Having both fields set results in Argo failing to sync, because they are mutually-exclusive. 
The docs already note that one of these fields must be set: https://truecharts.org/common/poddisruptionbudget/#name, so I do not think they should both be set by default, since it is more prone to error.
⚒️ Fixes  # 
**📃 Notes:**
---
Those checkboxes are …

fix(pdb): remove default maxUnavailable/minAvailable values
